// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Backup.Infrasctructure.DbContexts;

#nullable disable

namespace Modules.Backup.Infrasctructure.Migrations
{
    [DbContext(typeof(DbBackupScheduleContext))]
    partial class DbBackupScheduleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Modules.Backup.Core.Models.DbContext.BackupSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BackupIntervalInMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextBackupDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WordDaysId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkHoursId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Modules.Backup.Core.Models.DbContext.BackupWorkDays", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFridayWorking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMondayWorking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSaturdayWorking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSundayWorking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsThursdayWorking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTuesdayWorking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWednesdayWorking")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkDays");
                });

            modelBuilder.Entity("Modules.Backup.Core.Models.DbContext.BackupWorkHours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte>("EndHour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("StartHour")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkHours");
                });
#pragma warning restore 612, 618
        }
    }
}
